version: '3.1'
services:
  stats-server:
    build: ./stats-service/server
    image: stats_service_image
    container_name: stats-service
    depends_on:
      - stats-db
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/statsdb


  stats-db:
    image: postgres:14-alpine
    container_name: statsdb
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=statsdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
